version: 2

jobs:
  lint:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:ddc5257110beead59f268b8120abd0da286956e4aa15a45541b6834aca056295
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:ddc5257110beead59f268b8120abd0da286956e4aa15a45541b6834aca056295
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run flow

  test:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:ddc5257110beead59f268b8120abd0da286956e4aa15a45541b6834aca056295
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Tests & Check Coverage
          command: yarn run test:coverage

  build:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:ddc5257110beead59f268b8120abd0da286956e4aa15a45541b6834aca056295
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build
