version: 2

jobs:
  lint:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:617fe486859291275ec7ee6b26586281de2f01fc1d7517077d7bedd48b726b1f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:617fe486859291275ec7ee6b26586281de2f01fc1d7517077d7bedd48b726b1f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run flow

  test:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:617fe486859291275ec7ee6b26586281de2f01fc1d7517077d7bedd48b726b1f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Tests & Check Coverage
          command: yarn run test:coverage

  build:
    working_directory: ~/materialize-react
    docker:
      - image: circleci/node:8@sha256:617fe486859291275ec7ee6b26586281de2f01fc1d7517077d7bedd48b726b1f
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build
